name: commit-artifact

on:
  push:
    branches: [master, "dev-*"]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Upload to Blob Storage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t network-bastion .
          id=$(docker create network-bastion)
          docker cp $id:/app/target/release/azure-bastion-tunnel azure-bastion-tunnel
          docker rm -v $id
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: upload
        run: az storage blob upload --overwrite --name azure-bastion-tunnel-master/azure-bastion-tunnel-${{ steps.date.outputs.date }} --file azure-bastion-tunnel --container-name github-artifacts --account-name cedric05artifacts  --auth-mode login
